config/routes.rb
Feeder::Application.routes.draw do
  resources :feeds, :only => [:index] do
    post 'show', :on => :collection
  end

  root :to => "feeds#index"

end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  attr_accessible :fields, :guid
  serialize :fields, Hash

  def self.parse(params)
    params['additional'].to_s.split(' ').each {|v| Feedzirra::Feed.add_common_feed_entry_element(v, :as => v.gsub(/:/, "_"))}
    proceed(Feedzirra::Feed.fetch_and_parse(params['url']).entries)
  end

  def self.proceed(entries)
    entries.map do |entry|
      self.where(:guid => entry.id).first_or_create do |obj|
        obj.fields = entry.instance_values.except("entry_id")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :proc_list, :only => :show

  def index

  end

  def show
    @feeds = FeedEntry.parse(FEEDS[params[:feed][:name]])
  end

private
  def proc_list
    redirect_to :root if FEEDS[params[:feed][:name]].blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def print_feed(feed)
    hash = feed.fields
    url = hash.delete('url')
    title = hash.delete('title')
    date = hash.delete('published')

    raw <<-EOF
      <div>
        <p>(#{date}) #{link_to_if url.present?, title, url}</p>
        #{hash.map {|k, v| proceed_elem(k, v) }.join}
      </div>
    EOF
  end

private
  def proceed_elem(key, value)
    if (value.is_a?(Array))
      <<-EOF
        <p>#{key}
          <ul>#{value.map {|child| "<li>#{child}</li>"}.join}</ul>
        </p>
      EOF
    else
      "<p>#{key} : #{value}</p>"
    end
  end
end

app/views/feeds/_head.html.haml
= form_for :feed, :url => feeds_path do |f|
  = f.label "Select RSS"
  = f.select :name, options_from_collection_for_select(FEEDS, :first, :first)

  = f.submit "Get"

app/views/feeds/index.html.haml
= render :partial => 'feeds/head', :locals => {:@feed_lists => @feed_lists}

app/views/feeds/show.html.haml
= render :partial => 'feeds/head', :locals => {:@feed_lists => @feed_lists}

.feeds
  - @feeds.each do |feed|
    .feed
      = print_feed feed

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Feeder
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield